### Makefile --- 

## Author: shell@debian.debian
## Version: $Id: Makefile,v 0.0 2010/01/20 17:11:23 shell Exp $
## Keywords: 
## X-URL: 

build:
	emacs -Q -L . --batch -f batch-byte-compile *.el

clean:
	rm -rf *.elc

### Makefile ends here
